require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
Style/Documentation:
  Exclude:
    - db/migrate/*
RSpec/DescribeClass:
  Exclude:
    - spec/rake/import_dataset_spec.rb
    - spec/views/**/*
Metrics/BlockLength:
  Max: 28
RSpec/MultipleMemoizedHelpers:
  Exclude:
    - spec/models/prompt_spec.rb
RSpec/MultipleExpectations:
  Exclude:
    - spec/models/prompt_spec.rb
