version: "3.7"

x-app: &app
  build: .
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
    - rails_cache:/app/tmp/cache
    - bundle:/usr/local/bundle
  environment:
    EDITOR: vim
    RAILS_LOG_TO_STDOUT: 1
    PG_ROOT_PASSWORD: root
    PG_DATABASE: cgtrader_development
    PG_USER: postgres
    PG_PASSWORD: postgres
    PG_HOST: cgtrader-db
    PG_PORT: 5432
services:
  app:
    <<: *app
    ports:
      - "3000:80"
    depends_on:
      - cgtrader-db
      - elasticsearch

  cgtrader-db:
    image: postgres:14.0-alpine3.14
    ports:
      - "5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data/mydata
    environment:
      PG_ROOT_PASSWORD: root
      PG_DATABASE: cgtrader_development
      PG_USER: postgres
      PG_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/mydata
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.16
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
    environment:
      - node.name=es
      - cluster.name=cluster
      - discovery.seed_hosts=es
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - http.port=9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data
    restart: always
    ports:
      - 9200:9200

volumes:
  rails_cache:
  bundle:
  es:
